# Generated by Django 3.2.8 on 2023-01-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_alter_meet_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGateway',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_code', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('P', 'Pediente'), ('D', 'Hecho'), ('C', 'Cancelado')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ManyToManyField(to='meet.PayGateway')),
                ('meet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meet.meet')),
            ],
        ),
    ]
