# Generated by Django 3.2.8 on 2023-01-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_pay_paygateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygateway',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
