# Generated by Django 3.2.8 on 2023-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_auto_20230125_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='server',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='temporal_timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='meet',
            name='ct_email_patient_send',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='ct_email_therapist_send',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('T', 'Temporal'), ('U', 'Pago Pediente'), ('D', 'Confirmado'), ('C', 'Cancelado'), ('R', 'Reprogramado'), ('P', 'Presente'), ('A', 'Ausente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pay',
            name='status',
            field=models.CharField(choices=[('P', 'Pediente'), ('D', 'Hecho'), ('C', 'Cancelado'), ('R', 'Reembolsado')], max_length=1),
        ),
    ]
