# Generated by Django 3.2.8 on 2023-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_auto_20230308_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
