# Generated by Django 3.2.8 on 2023-03-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_alter_meet_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=1000, null=True)),
                ('account_id', models.CharField(max_length=1000, null=True)),
                ('client_id', models.CharField(max_length=1000, null=True)),
                ('client_secret', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meet',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ZoomMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, null=True)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.meet')),
            ],
        ),
    ]
