# Generated by Django 3.2.8 on 2024-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0017_alter_meet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='ct_email_patient_quality_survey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='ct_email_patient_remember',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='ct_email_therapist_quality_survey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='ct_email_therapist_remember',
            field=models.IntegerField(default=0),
        ),
    ]
