# Generated by Django 6.0.3 on 2026-03-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone", models.IntegerField(default=0, null=True)),
                ("timezone_verbose", models.CharField(default="UTC", max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Terapeuta",
                "verbose_name_plural": "Terapeutas",
            },
        ),
        migrations.CreateModel(
            name="RangeAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.IntegerField(default=0)),
                ("begin", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapist.therapist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GridAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone", models.IntegerField(default=0)),
                ("rate", models.IntegerField(default=20)),
                ("monday", models.CharField(default="", max_length=1500)),
                ("tuesday", models.CharField(default="", max_length=1500)),
                ("wednesday", models.CharField(default="", max_length=1500)),
                ("thursday", models.CharField(default="", max_length=1500)),
                ("friday", models.CharField(default="", max_length=1500)),
                ("saturday", models.CharField(default="", max_length=1500)),
                ("sunday", models.CharField(default="", max_length=1500)),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapist.therapist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Freeday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapist.therapist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Día libre",
                "verbose_name_plural": "Días libres",
            },
        ),
    ]
