# Generated by Django 6.0.3 on 2026-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=100)),
                ("rate", models.IntegerField(default=40)),
                ("interval", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name": "Configuración de agenda",
                "verbose_name_plural": "Configuraciones de agenda",
            },
        ),
    ]
