# Generated by Django 6.0.3 on 2026-03-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0002_scheduleconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Libre"),
                            ("T", "Temporal"),
                            ("U", "Pago pendiente"),
                            ("D", "Confirmado"),
                            ("R", "Reprogramado"),
                            ("C", "Cancelado"),
                            ("P", "Presente"),
                            ("A", "Ausente"),
                        ],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapist.therapist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
            },
        ),
    ]
