# Generated by Django 6.0.3 on 2026-03-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
        ("therapist", "0003_add_meet_and_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="meet",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patient.patient",
            ),
        ),
    ]
