# Generated by Django 3.2.8 on 2024-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timezone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
