# Generated by Django 3.2.8 on 2023-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
