# Generated by Django 3.2.8 on 2024-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='timezone_verbose',
            field=models.CharField(default='UTC+00:00', max_length=500),
        ),
    ]
