# Generated by Django 3.2.8 on 2024-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_timezone_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='timezone_verbose',
            field=models.CharField(default='UTC+00:00', max_length=1000),
        ),
    ]
