# Generated by Django 3.2.8 on 2022-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.CharField(default='Confirmado', max_length=100),
        ),
    ]
