# Generated by Django 3.2.8 on 2023-01-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('meet', '0002_meet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
