# Generated by Django 3.2.8 on 2023-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_paygateway_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='value',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meet',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='rate',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(default='Temporal', max_length=100),
        ),
    ]
