# Generated by Django 3.2.8 on 2023-01-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_auto_20230120_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='gateway',
        ),
        migrations.AddField(
            model_name='pay',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meet.paygateway'),
        ),
    ]
