# Generated by Django 3.2.8 on 2023-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_auto_20230317_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeet',
            name='zoom_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
