# Generated by Django 3.2.8 on 2023-06-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_zoommeet_zoom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='interval',
            field=models.IntegerField(default=5),
        ),
    ]
