# Generated by Django 3.2.8 on 2023-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_config_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='support',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
