# Generated by Django 3.2.8 on 2023-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_config_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='support_wa',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('T', 'Temporal'), ('U', 'Pago Pediente'), ('D', 'Confirmado'), ('R', 'Reprogramado'), ('C', 'Cancelado'), ('P', 'Presente'), ('A', 'Ausente')], max_length=1),
        ),
    ]
