# Generated by Django 3.2.8 on 2024-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0015_auto_20231006_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='timezone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
