# Generated by Django 3.2.8 on 2024-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0016_meet_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('F', 'Libre'), ('T', 'Temporal'), ('U', 'Pago Pediente'), ('D', 'Confirmado'), ('R', 'Reprogramado'), ('C', 'Cancelado'), ('P', 'Presente'), ('A', 'Ausente')], max_length=1),
        ),
    ]
