# Generated by Django 3.2.8 on 2023-06-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentquestions',
            old_name='ask',
            new_name='aswer',
        ),
    ]
