# Generated by Django 3.2.8 on 2023-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_ask_frequentquestions_aswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentquestions',
            old_name='aswer',
            new_name='answer',
        ),
    ]
