# Generated by Django 3.2.8 on 2023-05-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=1000)),
                ('subtitle', models.CharField(default='', max_length=1000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
        migrations.CreateModel(
            name='SectionHero',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.section')),
                ('image', models.ImageField(null=True, upload_to='section/hero')),
            ],
            bases=('page.section',),
        ),
        migrations.CreateModel(
            name='SectionPromo',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.section')),
                ('text', models.CharField(default='', max_length=1000)),
            ],
            bases=('page.section',),
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.CharField(default='', max_length=1000)),
                ('stars', models.IntegerField(default=5)),
                ('client_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='section/photo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('title', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1000)),
                ('ask', models.CharField(default='', max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('icon', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.section')),
            ],
        ),
    ]
