# Generated by Django 3.2.8 on 2022-12-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=20)),
                ('monday', models.CharField(max_length=1500)),
                ('tuesday', models.CharField(max_length=1500)),
                ('wednesday', models.CharField(max_length=1500)),
                ('thursday', models.CharField(max_length=1500)),
                ('friday', models.CharField(max_length=1500)),
                ('saturday', models.CharField(max_length=1500)),
                ('sunday', models.CharField(max_length=1500)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='Freeday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
    ]
