# Generated by Django 3.2.8 on 2024-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_freeday_gridavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridavailability',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
