# Generated by Django 3.2.8 on 2024-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_gridavailability_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='timezone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='timezone_verbose',
            field=models.CharField(default='UTC+00:00', max_length=500),
        ),
    ]
