# Generated by Django 3.2.8 on 2024-07-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_auto_20240515_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='timezone_verbose',
            field=models.CharField(default='UTC', max_length=500),
        ),
        migrations.CreateModel(
            name='RangeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(default=20)),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
        ),
    ]
