# Generated by Django 3.2.8 on 2021-11-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='root', max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='manager')),
                ('title', models.CharField(default='Nombre', max_length=200, null=True)),
                ('background', models.ImageField(null=True, upload_to='manager')),
            ],
        ),
    ]
